---
apiVersion: v1
kind: Secret
metadata:
  name: kener-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2tlbmVyOmtlbmVyQGtlbmVyLXBvc3RncmVzOjU0MzIva2VuZXI= # Change this to your database URL. Only needed when using a database (encoded in base64: "postgresql://kener:kener@kener-postgres:5432/kener")
  KENER_SECRET_KEY: V01qS3czNVFQak1wU0dWZlpWcGQz # Change this to a strong, long, random string! (encoded in base64: "WMjKw35QPjMpSGVfZVpd3")
