---
apiVersion: v1
kind: Secret
metadata:
  name: kener-secret
type: Opaque
data:
  DATABASE_URL: "postgresql://kener:kener@kener-postgres:5432/kener" # Change this to your database URL
  KENER_SECRET_KEY: "WMjKw35QPjMpSGVfZVpd3" # Change this to a strong, long, random string!
