---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kener

resources:
  - kener-secret.yaml
  - smtp-secret.yaml
  - kener-db-pvc.yaml
  - kener-pvc.yaml
  - deployment.yaml
  - service.yaml
#  - cluster.yaml -> Uncomment to enable CNPG Postgres cluster
#  - cluster-secret.yaml -> Uncomment to enable CNPG Postgres cluster
