---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
type: Opaque
data:
  SMTP_USER: ZVc5MWNrQmxiV0ZwYkM1amIyMD0= # base64 encoded: "your@email.com"
  SMTP_PASS: eW91cnBhc3N3b3Jk # base64 encoded: "yourpassword"
  SMTP_FROM_EMAIL: S2VuZXIgPHlvdXJAZW1haWwuY29tPg== # base64 encoded: "Kener <your@email.com>"
