- name: Google Search
  description: Search the world's information, including webpages, images, videos and more.
  tag: "google-search"
  image: "/google.png"
  api:
    method: GET
    url: https://www.google.com/webhp
- name: Svelte Website
  description: Cybernetically enhanced web apps
  tag: "svelte-website"
  api:
    method: GET
    url: https://svelte.dev/
  image: "/svelte.svg"
- name: Earth
  description: Our blue planet
  tag: "earth"
  defaultStatus: "UP"
  image: "/earth.png"