title: "Scriptor-Artis"
home: "/"
logo: "/sa.png"
github:
  owner: "Scriptor-Group"
  repo: "kener"
  incidentSince: 48
metaTags:
  description: "Kener: Open-source modern looking Node.js status page tool, designed to make service monitoring and incident handling a breeze. It offers a sleek and user-friendly interface that simplifies tracking service outages and improves how we communicate during incidents. And the best part? Kener integrates seamlessly with GitHub, making incident management a team effortâ€”making it easier for us to track and fix issues together in a collaborative and friendly environment."
  keywords: "Node.js status page, Incident management tool, Service monitoring, Service outage tracking, Real-time status updates, GitHub integration for incidents, Open-source status page, Node.js monitoring application, Service reliability, User-friendly incident management, Collaborative incident resolution, Seamless outage communication, Service disruption tracker, Real-time incident alerts, Node.js status reporting"
hero:
  title: Scriptor-Artis Status
categories:
  - name: Website
    description: "Scriptor-Artis website status"