title: "Heimdall Status Page"
home: "/"
logo: "/logo.png"
github:
  - owner: "NovoNordisk-OpenSource"
    repo: "kener"
    incidentSince: 48
metaTags:
  description: "This is Heimdall Status Page. Check the status of all Heimdall capabilities"
nav:
  - name: "Documentation"
    url: "/docs"
categories:
  - name: Non-Production
    description: "Heimdall Non-Production"
hero:
  title: Heimdall Status Page
  subtitle: Check the status of all Heimdall capabilities
i18n:
    defaultLocale: "en"
    locales:
        en: "English"
        hi: "हिन्दी"
        zh-CN: "中文"
        ja: "日本語"
        vi: "Tiếng Việt"
pattern: "squares"
barRoundness: SHARP
summaryStyle: CURRENT
barStyle: PARTIAL